import React from 'react';

const TermsConditions = () => {
    return (
        <div>
            <pre>
            RESERVATIONS: Please visit www.passiongetawaysllc.com, www.facebook.com/PassionGetaways, or call Passion Getaways at (770)616-2077 or contact us via email at info@passiongetawaysllc.com

IDENTIFICATION: Guests are required to make reservations in the full name that is listed on his/her government document they will use for travel. If you need to make any changes to a name after travel documents have been issued, clients will be responsible for all name change fees, if applicable.

PAYMENTS: Our merchant account is with Square. This will allow our clients to make payments using major credit cards.  No other form of payment is accepted at this time.

REFUNDS: All payments to Passion Getaways are non-refundable and non-transferable. This is because Passion Getaways has contractual agreements with hotels, airlines and other vendors that will not allow us to obtain any refunds. This way we can keep our package prices competitive and allow you to make monthly payments on your vacation.

ROOMMATE MATCHING: Roommate matching is available for our International Tours only. You will be matched with a roommate once you have paid more than 75% of the balance of your travel reservations and provided the person you will be matched with has also paid 75% of his/her balance. After you have submitted a profile and when 75% of your reservation has been paid, you will begin to receive email notifications from Passion Getaways with the name, email address, and profile of other solo travelers on your tour that have also expressed an interest in finding a roommate. Your information will, in turn, be provided to those same solo travelers. You will have two weeks to select to roommate and notify Passion Getaways.

PASSPORTS AND VISAS: Passengers are responsible for ensuring that they have the proper travel documents and MUST CHECK with the respective consulate(s) or a visa agency to determine whether any visas or passports are required. Passports are required to be valid for at least 6 months after the date of travel. Some countries require a full blank “VISA” page in the passport for stamping purposes. Any information provided on travel description pertains to US citizens only. Non-US citizens should check with the respective consulate of the country(s) to be visited for current entry requirements. We strongly suggest all cruise passengers to have a valid passport in their possession while cruising.

TRAVEL PROTECTION: Missing a vacation is bad enough. Losing the money you paid for your vacation is even worse. Therefore, we highly recommend Travel Protection that helps provide coverage for Trip Cancellation, Interruption, Baggage Loss or Delay, Medical Expenses and more. You are required to select and purchase travel insurance yourself for domestic and international tours. For Caribbean, Mexico and Cruise Tours, we can add travel insurance to your package when making your reservations.

TRAVEL DOCUMENTS: Provided full payment is received no later than your Final Payment Due date, travel documents and travel instructions will be sent via email and/or mail 30 days or earlier prior to travel. If paper documents are requested when e-documents are available, documents will be delivered via USPS approximately 14-21 days prior, and a fee of $30 will apply. A complete street address is required (no PO boxes).

CHILDREN: All children under 18 must be accompanied by an adult. The minimum age for children on most tours is 6 months. The minimum age for South Africa and Dubai Tours is 12. The minimum age for European Tour programs is 12. The minimum age for cruise tours is 6 months old and child must sail in a cabin with an adult over the age of 25 years of age. Discounts for children sharing a room as the third person may apply to children under 12 at some resorts on Caribbean and Mexico Tours. Accompanying adults are responsible for the safety of their children including providing any necessary safety equipment (such as infant/child seats) where appropriate. Please note that many countries have adopted practices to prevent international abductions of children. If a person under the age of 18 years will be traveling with an adult other than his/her parents, or with only one parent, a notarized letter written by the parents, or non-traveling parent, granting authorization to travel, including the dates of travel should be carried.

PRICES: All prices listed are per person based upon shared twin room occupancy unless otherwise clearly specified. Prices do not include items of a personal nature such as laundry, wines, water, beverages, food (other than at all-inclusive resorts or where clearly specified), passport and visa fees, insurance, and foreign port taxes unless specifically indicated in the package inclusions. Prices are correct at time of publication; however, as airfares continually fluctuate and classes of service may have limited capacity, tour package prices and availability will change accordingly. In case of human or computer error, Passion Getaways reserves the right to re-invoice for the correct price or service. A full refund will be made to passengers who choose not to pay an increase, provided Passion Getaways receives a written cancellation within five days of the price increase notification.

________________________________________

PAYMENTS & CANCELLATION

Deposit: A deposit is due at the time of reservation. All deposits are non-refundable and non-transferrable. All reservations (except where specified) will require a deposit and will be clearly noted the amount due and monthly payment plan.

Full Payment: All reservations can be paid in full at time of booking as long as the tour still has available space.

Late Payment: If there is any outstanding balance by the Final Payment Due date listed on your invoice, a late fee will automatically be added to your invoice one day after your final payment date. Late fees vary. Please see each individual tour description for late fee cost.

Reinstatement of Reservations: If your travel reservations have been cancelled, and you notify us within 14 days that you want to reinstate your reservations, a service reinstatement fee of $50 ($200 for international tours) will be added to your invoice and must be paid in advance in order to apply for reconfirmation of services.

Last Minute Reservations: All reservations must be made no later than 30 days prior to departure. If requested services cannot be confirmed, payment will be refunded. If services are confirmed, final payment is due within 24 hours and all applicable cancellation penalties will apply.

Form of Payment: Major credit cards or debit cards only. All payments made within 30 days of departure must be made by credit or debit card only. Credit card charges will be accepted by phone or online to fulfill the non-refundable deposit required. There is a $50 fee for all dishonored transactions.

Refunds: If you purchased Travel Insurance through any carrier, you will need to go through the process of your selected carrier.  There is an $25 processing fee that will not be refunded regardless of insurance carrier or not.

Cancellation: Once reservations have been made, cancellations will only be accepted in writing. Email your cancellation request to billing@passiongetawaysllc.com with your invoice number, full name, and date of travel. If you do not receive an acknowledgment within 48 hours, please call (770)616-2077 to ensure your information was received.

Reservation Changes: Changes to an existing reservation, whatever the cause, will incur a $50 per person charge plus any additional supplier fees. This includes name changes* and removal of any services such as optional tours and transfers. *Please note that name changes to airline reservations are subject to full cancellation and rebooking. Replacing a traveling passenger with another traveling passenger constitutes a cancellation, subject to cancellation penalties, and is not covered by this Reservation Changes policy. Changes or additions after departure are subject to local rates at the time of amendment and must be paid directly by the passenger to the service provider. There are no refunds for unused services.

________________________________________

TRAVELERS WITH DISABILITIES

In order to fully enjoy your Passion Getaways tour, we recommend that you select a trip that is suitable to your physical capabilities. Tour participants requiring any form of assistance, including travelers with physical disabilities, sight or hearing impairments, are required to notify Passion Getaways prior to reservation for review and our agreement. Additionally, the tour participant must be accompanied by an individual responsible for providing those services. Tour managers, guides, drivers or other tours, hotel, ship personnel are not able to provide such assistance. In order to participate in escorted tours, passengers must be able to understand and follow instructions given by the Tour Director at all times, both for the successful operation of the tour as well as for their personal safety. Passion Getaways reserves the right to reject participation or remove any individual from a tour if a notification was not provided and/or when, in our sole judgment, continued participation would significantly hinder the services to be provided to all guests. Expenses, including cancellation fees and/or costs for alternate travel plans or to return home, will be the sole responsibility of the passenger. Escorted tours are fast-paced, often requiring long walks over uneven terrain. In the interests of group harmony, clients should be able to maintain the pace of the tour. Clients with special needs may be better served independently. Passion Getaways can suggest touring options based upon specific requirements.

Wheelchairs & Walkers: USA Tours: Pursuant to the Americans with Disabilities Act (the ADA), Passion Getaways seeks to accommodate disabled travelers to the extent possible and consistent with the specific tour itinerary. Nevertheless, you may find that certain tour features may not be accessible to the extent that you require a wheelchair, scooter, or other special equipment to participate. We cannot provide individual assistance to travelers with wheelchairs or other mobility devices. We regret that some itineraries cannot accommodate wheelchairs or motorized scooters. Passengers are required to advise Passion Getaways of their accessibility requirements prior to booking in order for Passion Getaways to determine if reasonable accommodations are available. Passion Getaways will endeavor to accommodate special access needs but does not guarantee that it will be able to do so in all cases.

International Tours: Hotels, sea and river cruises outside of the United States are not required to comply with ADA requirements and therefore may not have ramps, wide entryways or elevators to accommodate disabled passengers or devices such as wheelchairs, walkers, and motorized scooters. Due to physical constraints and space limitations, wheelchairs, walkers, and motorized scooters may not be taken aboard motor coaches and river cruises.

Service Animals: Service animals cannot be accommodated on international escorted tours. Passengers on USA escorted tours who require a service dog because of a disability should check with Passion Getaways prior to booking a tour.

________________________________________

AIRLINES: Passion Getaways is not responsible for the services and policies imposed by the airlines. Airline schedules and flights are subject to change without notice. Passion Getaways is not responsible for penalties incurred for tickets, international or domestic, not issued by Passion Getaways - Travel due to schedule and/or flight changes. Airline reservations completed online are subject to review and, should Passion Getaways deem it necessary, may be rebooked to match minimum connecting time requirements and/or tour package itineraries, in which case you will be notified immediately. Airlines reserve the right to demand immediate issuance of tickets whenever they determine that specific flights are heavily booked even when normal ticketing rules do not require tickets to be issued until a later date. In this instance, Passion Getaways will require immediate and full payment of the airfare. This situation overrides invoice terms and conditions and payment due dates. If full payment is not received, seats will be canceled by the airline and may not be available to be rebooked on the same flights or at the same airfare. Any replacement air arrangements and airfare will be the sole responsibility of the passenger.

Airline Tickets: Once full payment is received; Passion Getaways airline tickets will be issued and are fully non-refundable. Should airline tickets require to be issued earlier than the Final Payment due date, you may be required to pay a larger non-refundable deposit and/or complete full payment.

Airline Seat Assignments: The airlines bear sole authority of assigning seats on group flights. All Passion Getaways airline contracts are for economy class seats only. If you require another class of service, you may consider purchasing your own flights and purchasing your land only package from Passion Getaways.

________________________________________

Airline Frequent Flier Programs: Passengers are responsible to contact their airline directly regarding mileage eligibility and accrual. Airline frequent flier programs determine whether to award miles in part or total based on their own rules which are updated frequently. Some discounted or promotional airfares, as well as some code-share flights, are not eligible for mileage accrual. Some private airfares, such as a "Passion Getaways Airfare", are not eligible for mileage or may qualify for reduced mileage, even if the same airline class of service is eligible for full mileage when sold as an "Instant Purchase" published airfare. Not all published airfares are eligible for mileage. Passion Getaways will record frequent flier numbers when provided by the passenger prior to travel documents being issued. However, the addition of frequent flier numbers to airline records does not guarantee mileage eligibility which is at the sole discretion of each airline. Airline schedule changes may result in flights which were originally eligible for mileage accrual no longer being eligible. We highly recommend passengers to provide their frequent flier account information whenever checking in online and/or at the airport check-in desk. After travel has commenced, it is often not possible to apply for frequent mileage credit. Passengers are also responsible to determine whether previously earned mileage may be applied to flights to secure upgrades.

Contact Information: Pursuant to TSA Secure Flight requirements, passengers are responsible to provide Passion Getaways with their name as it appears on their passport (or other government-issued I.D. when traveling), date of birth, gender, address, phone number, email and fax data for all passengers. Passengers must ensure that names are correctly listed on their invoice. Passion Getaways will not be responsible for passengers who do not receive an invoice or documents or are denied boarding due to inaccurate information.

________________________________________

Airline Name Changes: Any name change including minor spelling corrections may require airline reservations to be canceled and rebooked. Reservations are subject to current availability and pricing at the time of rebooking. Once airline tickets are issued, subsequent name corrections will be subject to an airline rebooking fee which may be as much as the full value of the airline ticket plus a $50 revision fee per change. Passion Getaways will not be held responsible for the denial of services by a carrier due to any name discrepancy. Name changes must be advised in writing at customercare@passiongetawaysllc.com

________________________________________

Airline Taxes & Fuel Surcharges: If you purchased airfare, airline taxes and fuel surcharges are included. Prior to completion of full payment, there is a potential for a price increase(s) due to increases in government- levied taxes and fees and/or fuel surcharges. To avoid potential increases, you may choose to accelerate your final payment in order that your tickets may be issued. Once issued, airline tickets are no longer subject to potential increases but are fully non-refundable. Certain overseas domestic flights are subject to air taxes which can only be paid locally; in these cases, the specific flights and amounts of those taxes are indicated in our package presentation and pre-departure.

________________________________________

Schedule Changes: In the event of an airline schedule change, Passion Getaways will make every effort to inform passengers of the schedule change and new flight schedule prior to departure. Passion Getaways is not responsible for schedule changes including, when applicable, changes in routing and/or the number of stops in the itinerary. Passion Getaways is unable to provide compensation for schedule changes, seat assignment modifications, or cancellations implemented by an airline. In the event of any change in flight itinerary made directly between passengers and their airline, it is the passengers' responsibility to advise Passion Getaways of amended flight details in writing at customercare@passiongetawaysllc.com Passion Getaways cannot be held responsible for land services, including arrival and/or departure transfers, if flights are changed without its knowledge.

________________________________________

Hotel Accommodations: All rooms requested are standard twin-bedded (two single beds) rooms with private facilities unless you have specifically requested a king/double size bed. Please understand although we will make a bed type request on your behalf, bed types are subject to availability. Room selection in all cases is strictly at the discretion of the hotel's management on a run-of-house basis. Triple and quad occupancy rooms consist of two beds for cruises, where triple and quad rooms will consist of a twin bed for each person. Some single rooms are smaller than a standard room size. The number of persons accommodated does not dictate the room size. Although available at most 4 and 5-star hotels, use of air-conditioning abroad differs greatly from the United States. Many European hotels were built before central air-conditioning was introduced. Air-conditioning is often shut down at night and from the end until the start of the summer months. All hotel rates are based on Passion Getaways' agreements with its suppliers and are not negotiable. Hotel check-in time is generally not before 3:00 p.m. and check-out time are prior to noon. Please be sure that adequate arrangements for accommodations have been taken into consideration when a late-night flight is being used. If a day room is included in the itinerary, check-out will normally be 6:00 p.m. We reserve the right to make substitutions with hotels of equal standard. There will be no refunds for any difference in the cost of those accommodations.

Hotel & Cruise Profiles: Passion Getaways' hotel and cruise ship profiles are based upon information provided to Passion Getaways by hotel and cruise ship partners and their representatives, including images and descriptions of individual properties. Star-ratings may differ from country to country. Passion Getaways does its best to maintain current information, however, is not responsible for any inaccuracies, changes in description details or amenities, or images provided by third parties.

________________________________________

Meals: As specified in each itinerary. Meals are based on the hotel's or restaurant's buffet or set menu. In general, beverages are not included, unless specifically stated. Although Passion Getaways cannot make guarantees, every effort will be made to honor special dietary requests submitted in writing at least 4 weeks prior to departure at booking@passiongetawaysllc.com

________________________________________

Transfers: Transfers are provided as indicated for each tour by car, minibus, or motor coach provided airfare is purchased from Passion Getaways. If you purchase a land-only tour, or if you deviate from the arrival and/or departure dates as stated in the itinerary, you will have the responsibility to purchase your own transfer to the hotel. Your arrival transfer is guaranteed for up to one hour from your scheduled arrival time in order to compensate for minor delays. Passion Getaways or the transfer company will not be responsible for flight delays, for any reason, beyond one hour from your originally scheduled arrival time. In case of a delay, whether due to a flight delay, immigration and customs, or time spent reporting baggage damage or loss, it will be your responsibility to make other transfer arrangements such as a taxi. Transfer costs are not refundable and any additional expenses will be your responsibility. The cost of a transfer is more expensive than hiring a taxi, as a Passion Getaways transfer necessarily includes round trip service, or 'dead-leg', meaning that our driver must come to the airport, hotel or pier only to pick you up and necessarily loses a one-way fare. Often the places of call (airports, seaports, hotels) demand entrance and parking fees, where drivers may have to wait for up to an hour. Passion Getaways transfer drivers, while not employees of Passion Getaways, are reliable. They provide you with a full welcome service, transfer you to the correct location and are prepared to answer your questions along with your ride. Passengers comfortable hiring a taxi on their own and do not require assistance will save money.

________________________________________

Sightseeing & Itinerary: Will be operated by motor-vehicle, its size dictated by the number of participants. Passion Getaways tours have been designed to accommodate individuals as well as groups. Times listed in itineraries are approximate and meant only as guidelines. Some itineraries may have early morning start times for sightseeing in order to complete the touring during daylight hours or avoid afternoon heat in tropical and desert climates. It is your responsibility to arrive on time for all scheduled flights, cruises, and package components. Arriving late may be considered a "no-show", in which case you will not be eligible for a refund for the unused service(s). We cannot guarantee the number of passengers who will be on any given tour. You may find that you are traveling with a sizeable group or only with your own companions. Services, however, will remain constant no matter the number of tour participants. Persons requiring any assistance or who have any form of disability should refer to section "Travelers With Disabilities". On dates including, but not limited to religious holidays and national celebrations, some monuments and sites may be closed. On these occasions, touring itineraries may be amended to reflect these closures. Occasionally, during holidays and certain periods, and/or due to unforeseen circumstances including weather conditions there may be last-minute changes, sometimes after arrival, in affecting the sequence of the tour, locations visited and/or hotels. Therefore, we reserve the right to adjust the sequence and/or substitute any hotels with others of similar category. In such cases, there will be no cost adjustment. National monuments and tourist sites regularly undergo renovations, which can obscure the monument's view. No tour will be canceled due to renovations, however Passion Getaways will decide based on the conditions whether to amend an itinerary. Passion Getaways itineraries may contain suggestions for activities for your leisure time; these suggestions do not constitute an endorsement of any specific service provider and the decision to participate in any such activities should be made independently and with due consideration.

________________________________________

 

Rail: Once full payment is received, Passion Getaways will select train times, rail tickets will be issued and are fully non-refundable. Except where requested in writing prior to final payment. Passengers traveling with a group may not request alternative train times. Once issued, rail tickets are valid for the dates and times specified. Some exchanges must be done locally at the station due to fare restrictions. Changes may be subject to local charges, fees, and fare increases. Once the booked train has departed, changes are no longer possible nor can amendments be completed on board the train. Passion Getaways does not control seat assignments which are entirely at the discretion of the rail companies. Once rail tickets are issued they are fully non-refundable and non-changeable.

________________________________________

Group Harmony: To ensure the desired group synergy, Passion Getaways reserves the right to accept, reject or expel any individual who is deemed disruptive or incompatible with the interests of the group, including, but not limited to, individuals who are intoxicated and/or under the influence of drugs leading to a negative experience for the remainder of the group. Expenses, including cancellation fees and/or costs for alternate travel plans or to return home, will necessarily be borne by the passenger. All unused services are non-refundable.

________________________________________

CRUISES:

Ship & Itinerary Changes: Cruise itineraries and ships are subject to change without notice. Furthermore, cruise ships may be chartered and/or departure dates canceled, in which case all monies will be refunded. Passion Getaways takes no responsibility for ship substitutions or itinerary changes imposed by a cruise line and is not responsible for any losses you may incur including the issuance and/or cancellation of airline tickets or visa fees.

Medical Services: Many ships do not carry a doctor or nurse onboard. Should medical attention be required, local services will be contacted. Resulting charges will be the responsibility of the passenger. Passion Getaways and the cruise ship operator are not responsible for the services provided.

________________________________________

Health Requirements: Check with your healthcare provider for up-to-date requirements. You may also check the Centers for Disease Control (www.cdc.gov) and/or the World Health Organization (http://www.who.int/en/) for their recommendations. Required inoculations, if any, must be recorded by clients' health practitioner on a valid vaccination certificate which the client must carry for proof of inoculation where required. Individuals with heart disease, chronic illness, physical handicap, advanced pregnancy, or mental illness should not participate in these rigorous travel programs. Any person who arrives at the destination ill with apparent fever or becomes ill during the tour will be removed from the group and directed to a local medical facility for diagnosis. Only upon clearance by an accredited medical facility will that individual be allowed to resume group travel. All costs associated with medical treatment and related expenses such as additional hotel nights or transportation not included in the original itinerary will necessarily be borne by the passenger.

Please note that some countries may require aircraft cabin insecticide treatment for in-bound foreign flights. A list of such countries is available at:

http://www.dot.gov/.../avi.../aircraft-disinsection-requirements.

________________________________________

Luggage (Airlines): Checked bags are typically limited to a total dimension of 62 inches by adding length + width + height (example: 26"+26"+10" = 62”), and a maximum weight of 50 lbs (23kg). Many airlines apply charges for checked bags. Passion Getaways is not responsible for checked bag fees, excess luggage or weight charges levied by an airline. If your luggage is lost or damaged by the airlines, a baggage claim form MUST be filed with the carrier before leaving the airport. We recommend that you use brightly colored luggage tags, straps or other identifiers to help you locate your luggage upon arrival or to describe it if it is lost.

Luggage (Escorted Tours): All Passion Getaways escorted tour buses allow one piece of luggage per person, plus carry-on bag. Additional baggage will be subject to a handling charge of $100 per piece. As Passion Getaways will not be responsible for loss or damage to luggage and personal belongings, you MUST report any loss or damage immediately at the time of the incident and obtain a written report from the local authority for submission to your insurance provider. ________________________________________

 

Tipping: Complete tipping guidelines are as follows:

Drivers including private cars and motorcoach drivers: $5-$10 per person, per day Tour Guides: $10-$20 per person, per day

________________________________________

PASSENGER AGREEMENT: All passengers are required to complete a Passenger Agreement prior to travel and, by so doing, formally accept Passion Getaways’ Terms & Conditions. Passengers booking online will be required to complete the Passenger Agreement at the time of booking. Passengers booking via telephone will be provided a verbal review of the Passenger Agreement, which will be delivered via email shortly after the time of booking. Customers who are unable to receive and complete their Passenger Agreement via email may request the Agreement be provided via fax or mail. Travel documents will not be released without a completed Passenger Agreement. Passion Getaways reserves the right to cancel bookings and return deposits without a completed Passenger Agreement. The Passenger Agreement incorporates these Terms & Conditions including the following Release from Liability, Assumption of Risk and Binding Arbitration Clauses. Completion of the Passenger Agreement constitutes an agreement to these Travel Terms & Conditions and Passion Getaways’ Release from Liability, Assumption of Risk and Binding Arbitration Clause.

________________________________________

RELEASE FROM LIABILITY: Passion Getaways, its shareholders, directors, officers, employees and affiliates, (collectively "Passion Getaways") does not own or operate any entity which is to or does provide goods or services for your trip including, for example, ownership or control over hotels or other lodging facilities, airline, vessel, bus, van or other transportation companies, local ground operators, providers or organizers of optional excursions or equipment used thereon, food service or entertainment providers, etc. All such persons and entities are independent contractors. As a result, Passion Getaways is not liable for any negligent or willful act or failure to act of any such person or entity, or of any other third party. Without limitation, Passion Getaways is not responsible for any injury, loss, or damage to person or property, death, delay or inconvenience in connection with the provision of any goods or services occasioned by or resulting from, but not limited to, acts of God, acts of government, force majeure, acts of war or civil unrest, insurrection or revolt, strikes or other labor activities, criminal or terrorist activities of any kind, or the threat thereof, overbooking or downgrading of accommodations, structural or other defective conditions in hotels or other lodging facilities, mechanical or other failure of airplanes or other means of transportation or for any failure of any transportation mechanism to arrive or depart timely or safely, dangers associated with or bites from animals, pests or insects, marine life or vegetation of any sort, dangers incident to recreational activities such as swimming, kayaking, sailing, canoeing, rafting, hiking, walking, bicycling, etc., sanitation problems, food poisoning, lack of access to or quality of medical care, difficulty in evacuation in case of a medical or other emergency, illness, epidemics or the threat thereof or for any other cause beyond the direct control of Passion Getaways. In addition, I release Passion Getaways from its own negligence and assume all risk thereof.

ASSUMPTION OF RISK: I am aware that travel such as that I am undertaking involves hazardous activities, with a risk of illness, injury or death which may be caused by forces of nature, animals, insects or flora, the negligence of Passion Getaways, or other persons and companies known or unknown, or of willful or criminal conduct of third parties. I am aware that weather conditions may be severe, adverse and/or unpleasant. I am also aware that medical services or facilities may not be readily available or accessible during some or all of the time during which I am participating on the trip. In order to partake of the enjoyment and excitement of this trip, I am willing to accept the risks and uncertainty involved as being an integral part of my adventure. I hereby accept and assume full responsibility for any and all risks of illness, injury or death and of the negligence of Passion Getaways and agree to hold harmless and release Passion Getaways from claims of third-party negligence.

I understand the physical requirements of the activity in which I will be participating, and I currently have no known physical, medical or mental condition which would impair my ability to participate in this tour or my safety in this activity, and I am willing to assume all risks that may be created, directly or indirectly, by any such condition. I hereby authorize Passion Getaways or my local ground handler or others to arrange for any emergency medical treatment and hospitalization as may be necessary for me because of participation in this activity without my further consent.

BINDING ARBITRATION: I agree that any dispute concerning, relating or referring to this Agreement, the brochure or any other literature concerning my trip, or the trip itself, shall be resolved exclusively by binding arbitration pursuant to the Federal Arbitration Act, 9 U.S.C. §§1-16, either according to the then existing Commercial Rules of the American Arbitration Association (AAA) or pursuant to the Comprehensive Arbitration Rules & Procedures of the Judicial Arbitration and Mediation Services, Inc. (JAMS). Such proceedings will be governed by substantive (but not procedural) Georgia law and will take place in Atlanta, GA. The arbitrator and not any federal, state, or local court or agency shall have exclusive authority to resolve any dispute relating to the interpretation, applicability, enforceability, conscionability, or formation of this contract, including but not limited to any claim that all or any part of this contract is void or voidable. Please understand that by agreeing to these terms and conditions, you (and we) are waiving our right to a trial by jury.

VOLUNTARY PARTICIPATION: I acknowledge that I have voluntarily applied to participate on the trip designated on this application (or a trip which I may change to) and that I have read the description of the trip as it appears in the current Passion Getaways website relating to the trip, together with all information contained in this application. I am voluntarily participating in this trip with knowledge of the hazards involved.

KNOWING AND VOLUNTARY EXECUTION: I have carefully read these Terms and Conditions and the booking information sections of this document, and fully understand its contents. I am aware that this is a release of liability and a contract between myself and Passion Getaways and agree of my own free will. By signing, I agree to these Travel Terms & Conditions and Passion Getaways’ Release from Liability, Assumption of Risk and Binding Arbitration Clause for myself, each member of my traveling party and any minor children accompanying me.

PHOTOGRAPHIC RELEASE: Passion Getaways may take photographs or video of its trips and trip participants grant Passion Getaways permission to do so and for it to use same for promotional or commercial use without payment of any compensation to participant.

________________________________________


        </pre>
        <p>Go back to <Link to="/register"></Link></p>
        </div>
    );
};

export default TermsConditions;